### ISSUE TITLE
Resize not working

### ISSUE THREAD

**Issue by dMores** [cedaro/gravity-forms-iframe#19]
Hi,
lovely plugin, thank you for sharing.
However, I can't seem to get the frame resizing to work. 
The external site I'm embedding the form is not a WordPress site. I have a clean page with no layout, no CSS, no scripts and the iFrame stays at 500px (the height specified in the code).
Any ideas why? 
Thanks
Daniel

**Comment by mavedisian** [comment]
Same issue here.

**Comment by seamusiv** [comment]
Some websites do not support loading external javascript. I got this to work by including the javascript directly after the iframe code on the external page.

`<script type="text/javascript">
!function(t,e){"use strict";var n,a,i=document.getElementsByTagName("iframe");if(n=function(t,e,n){t.addEventListener?t.addEventListener(e,n,!1):t.attachEvent&&t.attachEvent("on"+e,n)},n(t,"message",function(t){var e,n,a=t.data.split(":");"size"===a[0]&&(e=a[1].split(","),n=i[e[0]],"undefined"!=typeof n&&(n.height=e[2],n.scrolling="no"))}),a=function(t){i[t].onload=i[t].onreadystatechange=function(){this.readyState&&"complete"!==this.readyState&&"loaded"!==this.readyState||setInterval(function(){i[t].contentWindow.postMessage("size?"+t,"*")},500)}},i.length)for(var s=0;s<i.length;s++)-1!==i[s].className.indexOf("gfiframe")&&a(s)}(this);
</script>`

**Comment by bradyvercher** [comment]
Closing due to a lack of activity. If this is still a problem, please feel free to reopen or start a new issue.
