### ISSUE TITLE
embed a form with paypal plugin

### ISSUE THREAD

**Issue by forgreenspa** [cedaro/gravity-forms-iframe#22]
I install gravity forms with paypal standard addons. I make a form with paypal payment. I installa Gravity Forms Iframe Add-On and the paypal forms doesn't work in a site where I embeded. Solutions?
THANKS

**Comment by bradyvercher** [comment]
Closing due to a lack of activity. If this is still a problem, please feel free to reopen or start a new issue.

**Comment by d7677** [comment]
Same here. Any solution for this? Only reason I am using the gravity forms iframe is to be able to embed a product into any site I need to. I also have the paypal standard add on. 

Form shows up but either PayPal sends a message that "paypal.com refused to connect" 

Page with iframe on it.... https://courageouskitchen.org/order-courageous-coffee/

Source website + form - https://brewourcoffee.com/courageous-kitchen/

Thoughts!?! 

Thanks in advance! 

<img width="1242" alt="screen shot 2018-12-01 at 1 32 50 pm" src="https://user-images.githubusercontent.com/45519901/49331591-b0211a80-f56d-11e8-836f-379d20240521.png">
<img width="1241" alt="screen shot 2018-12-01 at 1 32 31 pm" src="https://user-images.githubusercontent.com/45519901/49331592-b0211a80-f56d-11e8-97cc-425d2017be96.png">
