### ISSUE TITLE
Digital Signature doesn't work in a gravity-forms-iframe

### ISSUE THREAD

**Issue by RealityTVshows** [cedaro/gravity-forms-iframe#26]
I built a 3 page form with a digital signature at the bottom, the "box" in which to sign no longer appears...

**Comment by emanweb** [comment]
I am having the same problem... trying to figure out. I guess for some reason some of the signature add on are not included in the iframe. Did you find a work around?

**Comment by emanweb** [comment]
I added wp-content/plugins/gravityformssignature/super_signature/ss.js?ver=2.4 to the file gravity-forms-iframe.php and now it's working :) I guess need to add a conditional there to see if the add on is active and include this file.

**Comment by RealityTVshows** [comment]
Very cool, sounds good... thank you,

Paul
