### ISSUE TITLE
Fields hidden beneath keyboard on iOS Safari (not scrolling correctly)

### ISSUE THREAD

**Issue by amosarnold** [cedaro/gravity-forms-iframe#29]
Hi,

I'm still greatly appreciating this plugin! I do have an issue I wonder if can be improved?

When viewing a form using the plugin on iOS in Safari, the page is not scrolling to the focused field when hitting 'next' on the mobile keyboard. Rather the cursor advances to the next field, but it is hidden beneath the keyboard. 
I do NOT have the same issue when using Chrome on iOS, however I have a large amount of users on Safari :( .

I did check, and a regular Gravity form on my site inside of Wordpress (no iframe) does NOT have the same problem, it focuses correctly on each field.

Any ideas for me? 
The development page I'm working on right now is https://emethgym.com/classes%20copy.html

**Comment by bradyvercher** [comment]
Closing due to a lack of activity. If this is still a problem, please feel free to reopen or start a new issue.
