### ISSUE TITLE
Invalid Argument Supplied ... form_display.php line 2327

### ISSUE THREAD

**Issue by signaltheory** [cedaro/gravity-forms-iframe#31]
Hello. I'm getting an error message on my contact page:
http://www.signaltheory.com/contact
This has been an issue for the last few updates to Wordpress. I've searched and I see another couple of items on the same subject but the replies give no clue has to how to solve. Please help, and thanks.

**Comment by bradyvercher** [comment]
There were a few reports of a similar error, but they should have been fixed in the last release. Are you sure you're running the latest version?

**Comment by signaltheory** [comment]
Yes. I was just logged in and the plugin is updated. I ended up changing the wp-config file so that the error message doesn’t show, but that seems like a work-around and not a fix. Attached is a screen-shot of the error, fyi. 

Signal Theory
269 S. Beverly Drive, Ste. 242
Beverly Hills, CA  90212
310.393.0105 general
http://signaltheory.com <http://signaltheory.com/>

**Comment by bradyvercher** [comment]
It doesn't look like your screenshot made it through. I checked line 2327 in form_display.php in Gravity Forms and it doesn't look like that particular error message is possible on that line.

Can you let me know which version of Gravity Forms and the version of the iframe add-on that your'e using?

**Comment by signaltheory** [comment]
Yes, I looked at the code as well, and I can’t figure out what the problem is.

Gravity Forms Version 1.9.15
Gravity Forms Iframe Add-On Version 1.0.2

Attached is the screen shot again. Maybe your email server doesn’t accept attachments.


Signal Theory
269 S. Beverly Drive, Ste. 242
Beverly Hills, CA  90212
310.393.0105 general
http://signaltheory.com <http://signaltheory.com/>

**Comment by bradyvercher** [comment]
Closing due to a lack of activity. If this is still a problem, please feel free to reopen or start a new issue.
