### ISSUE TITLE
The server refused the connection.

### ISSUE THREAD

**Issue by mcostales84** [cedaro/gravity-forms-iframe#33]
I get a message with this error/

The server refused the connection.

What do you suggest?

**Comment by phillipwilhelm** [comment]
I'm having the same issue, getting a 500 error in Google Chrome Console. 

PHP Version	5.6.17-0+deb8u1	
MySQL Version	5.5.5	
WordPress Version	4.4.4	
Gravity Forms Version	1.9.18.3	


I have tried on the latest version of Gravity Forms and same issue. I removed NGinx params hoping that might help but no luck. I didn't find any errors either in the logs.

Ideas?

**Comment by bradyvercher** [comment]
I haven't encountered this myself and don't really have any ideas without more information. Let me know if you discover anything in your error logs, though.

**Comment by mcostales84** [comment]
I never make it work, and now I don't even remember where/why i needed this plugin.
Sorry

**Comment by bradyvercher** [comment]
Closing due to a lack of activity. If this is still a problem, please feel free to reopen or start a new issue.
