### ISSUE TITLE
Submit Button go to separate page

### ISSUE THREAD

**Issue by robertallenbaker** [cedaro/gravity-forms-iframe#34]
Hi, is there a code that will have the submit button go to a separate page?

**Comment by GlennJimerson** [comment]
That would be controlled through Gravity Forms.  It would be under the Form Settings > Confirmations >Edit .  At the top you'll see Confirmation Type.  Set it there.   If you don't want that new page to open inside the iframe just redirect to a page that has iframe busting Js on it.

**Comment by bradyvercher** [comment]
Closing due to a lack of activity. If this is still a problem, please feel free to reopen or start a new issue.
