### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by Fliktrax** [cedaro/gravity-forms-iframe#36]
PHP Fatal error:  Call to protected method GFAddOn::get_form_settings() from context 'GravityFormsIframe_Plugin' in  .../wp-content/plugins/gravity-forms-iframe/classes/Plugin.php on line 82

Am I missing something ...

**Comment by bradyvercher** [comment]
I believe that method was protected in an older version, but it should be public in the latest Gravity Forms release. What version do you have installed?

**Comment by Fliktrax** [comment]
I'm using Gravity Forms version 1.9.17.5 with WordPress 4.6.1

**Comment by Fliktrax** [comment]
Thanks for your help ... I just made that method public in  ... /gravityforms/includes/addon/class-gf-addon.php and that fixed the issue ... thanks again ...

**Comment by bradyvercher** [comment]
No problem @Fliktrax. I would recommend upgrading to the latest version of Gravity Forms instead of hacking the plugin file like that since it could potentially cause conflicts with other add-ons.

**Comment by Fliktrax** [comment]
Yeah ... I know it's a hack ... I'll update GF eventually but this was a last minute job. 

I want you to you know that you're plugin saved me about 2 days of programming for a virtual terminal that I didn't have re-invent!  Do you have a PayPal account so that donate I can return the favor? 

-Jamie
