### ISSUE TITLE
Submit to WP plugin repo?

### ISSUE THREAD

**Issue by hubdotcom** [cedaro/gravity-forms-iframe#38]
Can you submit this to the official repo?

**Comment by bradyvercher** [comment]
This was initially built for a client and is used as an internal tool, so I'll keep it updated as needed, but I don't have plans to release it on WordPress.org.

**Comment by hubdotcom** [comment]
Fair enough, could we get this committed? https://github.com/cedaro/gravity-forms-iframe/pull/37
