### ISSUE TITLE
causing gravityformsapi 404 in Wordpress 4.6.1

### ISSUE THREAD

**Issue by jimmykang** [cedaro/gravity-forms-iframe#40]
After a wordpress update to Wordpress 4.6.1, the gravity forms api is always getting a 404 if this plugin is enabled. If we disable this plugin, the gravityformsapi works as normal.

**Comment by scysys** [comment]
No problems here

**Comment by bradyvercher** [comment]
Closing due to a lack of activity. If this is still a problem, please feel free to reopen or start a new issue.
