### ISSUE TITLE
Removing scroll bar from gravity form Iframe

### ISSUE THREAD

**Issue by jmu289** [cedaro/gravity-forms-iframe#42]
Hi,
Could you help me figure out how to modify the IFrame to display without a scroll bar?
See this page: https://opt-insignup.leadpages.co/facebook-ad-practice-exam/

Notice how the gravity form on the right side of the page has a scroll bar? This happens whether I use this Iframe on a leadpage or on a regular HTML page. I can't figure out how to make the iframe work without using this scroll bar. I'd like it to work similar to this page http://associatepi.com/cpcu-and-api-practice-exam-downloads/

See how this page shows the entire gravity form and there's no need to scroll down?

I reached out to leadpages and they said:
"The change you're trying to make is specific to the HTML code that is provided. I would reach out to Gravity Forms and see if they can provide a version of that code that doesn't included the scrolling function."

This is the Iframe i'm using:
<iframe src="//associatepi.com/gfembed/?f=8" width="100%" height="500" frameBorder="0" class="gfiframe"></iframe>
<script src="//associatepi.com/wp-content/plugins/gravity-forms-iframe-master/assets/scripts/gfembed.min.js" type="text/javascript"></script>

Could you help me figure out how to use the gravity form without a scroll bar?

Thanks!

**Comment by seamusiv** [comment]
You need to add the following to your iframe code:

`scrolling="no"`

**Comment by bradyvercher** [comment]
Closing due to a lack of activity. If this is still a problem, please feel free to reopen or start a new issue.
