### ISSUE TITLE
Disable the admin bar by default 

### ISSUE THREAD

**Issue by robneu** [cedaro/gravity-forms-iframe#44]
It's possible for the admin bar to display in an embedded iframe if a user is logged in to the site where the embed exists. It's trivial to filter this on the site where the embed is set up, but maybe that should just be the default?

**Comment by bradyvercher** [comment]
Hey @robneu! The admin bar should already be [disabled here](https://github.com/cedaro/gravity-forms-iframe/blob/develop/classes/Plugin.php#L90). Is it possible something is re-enabling it where ever you encountered this?

**Comment by robneu** [comment]
🤔

Yeah, it must be getting bypassed due to another filter running on that site.

**Comment by robneu** [comment]
FWIW, replacing that line with `add_filter( 'show_admin_bar', '__return_false' );` resolves the issue for me. Maybe adding that super late like priority 100 or something would be more reliable? Not sure what other issues that might cause...

**Comment by bradyvercher** [comment]
As long as it's limited to the iframe requests it shouldn't be a problem. Want to submit a PR?

**Comment by robneu** [comment]
Sure thing. I'll send it through in a sec.

**Comment by bradyvercher** [comment]
Thanks!
