### ISSUE TITLE
Blank draft post created on form submit

### ISSUE THREAD

**Issue by CJau777** [cedaro/gravity-forms-iframe#48]
I seem to be getting a draft post (ie post-type: 'post') being created when a form that has been embedded using the iframe code from this plugin is submitted.

- Have deactivated all other plugins apart from Gravity Forms and Gravity Forms Iframe Add-on.  
- Theme is set back to Twentyfifteen (latest version).
- Wordpress version is 4.7.2 (latest version).
- Plugin version is 2.0.1 (latest version).

Any suggestions on what else may be causing this?

Edit: On further investigation, the issue appears to be caused by the "Custom Field" type (under Post Fields) being present in the form.

**Comment by bradyvercher** [comment]
Closing due to a lack of activity. If this is still a problem, please feel free to reopen or start a new issue.
