### ISSUE TITLE
Currency problem in total

### ISSUE THREAD

**Issue by frle33** [cedaro/gravity-forms-iframe#49]
I am using "Gravity Forms Multi Currency" plugin and it works fine, even in a classical frame.

But when using 'gravity-forms-iframe' plugin, currencies along the form are correct but the currency of the total field is the one coming from the general gravity settings, as you can see for example on the link below (the form is in € but the total is shown in £ (it should be in € too) : https://shopnbook.com/test-fin/
Any idea to correct that please to use this nearly 5* plugin? :-)
Thanks.

**Comment by frle33** [comment]
Any answer please?

**Comment by bradyvercher** [comment]
I took a brief glance at that currency plugin and your best bet is to use the `gfiframe_head` action to set the currency if the form has one. Something like this should handle it:

```php
add_action( 'gfiframe_head', function( $form_id, $form ) {
	if ( empty( $form['currency'] ) ) {
		return;
	}

	add_filter( 'gform_currency', function( $currency ) use ( $form ) {
		return $form['currency'];
	} );
}, 10, 2 );
```

**Comment by frle33** [comment]
Thank you very much Brady for your quick answer, it works!

**Comment by frle33** [comment]
Dear Brady Vercher,
Sorry to bother you, I have a question re. your iframe gravity form plugin.

Why once embeded, it seems we loose a piece of CSS, the layout of the 
dropdown for exemple is reduced, not so high and nice..
Look at this not embeded:

https://shopnbook.com/112319-loxdale/

and the same, once embeded please?

https://shopnbook.com/112319-loxdale-iframed/

Any idea please?
Thx

Best wishes
Franck


Le 02/03/2017 à 00:17, Brady Vercher a écrit :
