### ISSUE TITLE
No resize on Form submit with validation error(s).

### ISSUE THREAD

**Issue by rdytogokev** [cedaro/gravity-forms-iframe#50]
First thanks for this plugin.

I have some crazy long forms. When people fill it out and forget an important field, the form will give them a validation error message on Submit.  The problem is, they don't see the message. It is at the top of the form and they are way down at the bottom. The form does not shrink back and does not scroll up to the error message. They think everything is okay and leave the page. But in reality they have to fix the errors and resubmit. They don't know there are errors and leave the page with an un-submitted form.

What can I do?

**Comment by seamusiv** [comment]
Is your page loading the javascript to autosize? I'm not sure the script auto-resizes confirmation or error pages.

**Comment by bradyvercher** [comment]
Closing due to a lack of activity. If this is still a problem, please feel free to reopen or start a new issue.
