### ISSUE TITLE
iframe settings not showing up 

### ISSUE THREAD

**Issue by tobiaseigen** [cedaro/gravity-forms-iframe#52]
I have up to date wordpress 4.9.1 and gravityforms 2.2.5. Does this plugin work with that combination? Are there any known conflicts with other gravityform addons or wordpress plugins?
When following your installation instructions on the readme it appears to install correctly but the iframe form settings link does not show up on the form settings page as it seems it should based on your screenshot. 

I'd be grateful for any insight and guidance as your plugin would help me alot at this particular moment. :) Thanks! 

ps - I think the link to the plugin zip is incorrect in the readme. It links to your old repo at https://github.com/bradyvercher/gravity-forms-iframe/archive/master.zip

I tried that zip, the master zip here in this repo and the development zip here. None of them appear to work for me.

**Comment by tobiaseigen** [comment]
hah- I can solve my own issue. It was a wordpress role permission issue. for some reason, the admin role did not have permission to work with iframe. Enabled and presto! It works. Now on to testing to see how it works. :) Many thanks for this great plugin.

**Comment by bradyvercher** [comment]
Glad to hear you got it working, @tobiaseigen!

It's been awhile, but if I recall correctly, I think capabilities may need to be added if you have the Members plugin installed. You wouldn't happen to be using that plugin, would you?

**Comment by tobiaseigen** [comment]
yep - that's the one. thanks for the reply.
