### ISSUE TITLE
gform_after_submission not firing

### ISSUE THREAD

**Issue by daveryaaziem** [cedaro/gravity-forms-iframe#53]
I have a plugin that submit the form data to a remote db afther the 'gform_after_submission' action is called. It seems to fire on forms that is on the wordpress blog, but does not for forms that are iframed

**Comment by bradyvercher** [comment]
Unfortunately, I'm not aware of anything in this plugin that would prevent that action from firing, but let me know if you come across anything.

**Comment by daveryaaziem** [comment]
Is it possible that this plugin is somehow bypassing my plugin? Is there a way, that you know of, where your plugin can recognize my plugin? What I mean is, i notice that the iframe url is mydomain.com/gfembed/?f=formid is it possible that because of this url, my plugin is not being registered? If so, would you happen to know how I could fix this?

**Comment by bradyvercher** [comment]
Anything is possible, but without knowing how your code works, I'm not sure what the problem could be. When a request comes through for an embedded form, this plugin takes over at [`template_redirect`](https://github.com/cedaro/gravity-forms-iframe/blob/ffb91625e0910a847622efee65da29126b55fef5/classes/Plugin.php#L61-L116) and loads the [iframe template](https://github.com/cedaro/gravity-forms-iframe/blob/ffb91625e0910a847622efee65da29126b55fef5/templates/gravity-forms-iframe.php). There's not much more to it than that.
