### ISSUE TITLE
Smiley face at bottom of form on Mobile

### ISSUE THREAD

**Issue by SJNBham** [cedaro/gravity-forms-iframe#55]
When using this plugin, I'm seeing what seems to be a smiley face at the bottom of the form on mobile devices. Is this a function of the iframe script?

**Comment by bradyvercher** [comment]
No, that's not injected by the iframe script. It's most like from the Stats module in Jetpack. [This post has some information](https://jetpack.com/2014/06/18/how-to-install-stats-and-analytics-on-your-wordpress-site-with-jetpack/) about disabling that if you want to get rid of it.
