### ISSUE TITLE
iframe resize not working.

### ISSUE THREAD

**Issue by theshae** [cedaro/gravity-forms-iframe#56]
I created a basic html page: https://demo.webdiner.com/test.html to test. The form shows, but it is not auto resizing. Does this still work? Any ideas what could be wrong?

**Comment by bradyvercher** [comment]
It looks like you might be using the `develop` branch, which hasn't been released and doesn't contain a minified version of the resize script. Can you try the [latest release from here](https://github.com/cedaro/gravity-forms-iframe/releases) instead?

**Comment by jbaarends** [comment]
I find the same problem with resizing at http://www.jaapbaarends.nl/test-iframe/ Any ideas what I'm doing wrong?

(I totally understand if you don't have the time to look into this)
