### ISSUE TITLE
Iframe works on desktop but not mobile

### ISSUE THREAD

**Issue by lherronSe** [cedaro/gravity-forms-iframe#63]
Hi there, this iframe for Gravity forms is a big help for our nonprofit with a wordpress website, but a separate software/host for donations. Currently, I've set up a project on the donor software that includes an iframe of a form linking back to our wordpress gravity forms. However, I can't see the iframe on mobile, which is a problem for us, because most users will probably be opening this on there phones... Can you help? 
Project Page link below:
https://give.serge.org/p-711-giving-tuesday-double-bless-your-missionary.aspx

**Comment by bradyvercher** [comment]
It looks like you have a CSS rule in `z-so-style.css` that's hiding iframes on mobile:

```css
@media (max-width: 720px)
#soProjectDetailPage iframe {
    display: none;
}
```

If you remove or override that, it should allow the iframe to show on mobile.

**Comment by lherronSe** [comment]
Hey Brady, I saw that as well, but I'm having difficulty getting the
company that holds the z-so-style.css I tried already to override it in the
html box that I'm able to input code, however it just doesn't seem to
work...

I've input this:

@media (max-width: 720px)
#soProjectDetailPage iframe {
    display: block;
}

and tried a couple other options of this, but none of them seemed to work.
Thoughts?

__________________________________________
*Luke Herron | Digital Media Specialist*
101 West Avenue, Suite 305 | Jenkintown, PA 19046-2039 | USA
347.994.6717 | *serge.org* <http://serge.org/>
*Serge *| *Grace at the Fray*

You can help *open doors in closed countries*
<https://give.serge.org/p-705-open-doorsin-closed-countries.aspx?source=19ES01B4T>
*. *Find out more here
<https://give.serge.org/p-705-open-doorsin-closed-countries.aspx?source=19ES01B4T>
!

**Comment by bradyvercher** [comment]
It depends on the order that your custom CSS loads, so that may not always work. You can try making the selector more specific or throw an `!important` in there.

```css
@media (max-width: 720px)
#soProjectDetailPage iframe {
    display: none !important;
}
```

**Comment by lherronSe** [comment]
hmm... I've tried
@media (max-width: 720px)
#soProjectDetailPage iframe {
 display: 100% !important;
   }

How would I make the selector more specific?
__________________________________________
*Luke Herron | Digital Media Specialist*
101 West Avenue, Suite 305 | Jenkintown, PA 19046-2039 | USA
347.994.6717 | *serge.org* <http://serge.org/>
*Serge *| *Grace at the Fray*

You can help *open doors in closed countries*
<https://give.serge.org/p-705-open-doorsin-closed-countries.aspx?source=19ES01B4T>
*. *Find out more here
<https://give.serge.org/p-705-open-doorsin-closed-countries.aspx?source=19ES01B4T>
!

**Comment by lherronSe** [comment]
Finally got help from their support team which gave me this as a fix:

@media (max-width: 720px){
    #soProjectDetailPage iframe.iframeAtt {
        display: block;
    }
}

And it worked! I'm guessing because I had added styling to the iframe
already, I could use the same more specific selector for less than 720px
width. Thanks for your insight!
__________________________________________
*Luke Herron | Digital Media Specialist*
101 West Avenue, Suite 305 | Jenkintown, PA 19046-2039 | USA
347.994.6717 | *serge.org* <http://serge.org/>
*Serge *| *Grace at the Fray*

You can help *open doors in closed countries*
<https://give.serge.org/p-705-open-doorsin-closed-countries.aspx?source=19ES01B4T>
*. *Find out more here
<https://give.serge.org/p-705-open-doorsin-closed-countries.aspx?source=19ES01B4T>
!

**Comment by bradyvercher** [comment]
Glad to hear you got it working! Their suggestion is an instance of making the selector more specific, so it's nice to see that worked.
