### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by Clickprophotographers** [cedaro/gravity-forms-iframe#73]
None of our forms load anymore. 
https://apply.clickprophotographers.com/application-1

**Comment by maxwellrowe** [comment]
Just a note that I got this working with latest Gravity Forms and WP by modifying the plugin.

Within the plugin files, go to /classes/Addon.php

- Change line 167 from private to public function
`public function settings_iframe_embed_code( $field, $echo = true ) {`

- Commented out line 173
`//$attributes[] = 'readonly="readonly"';`

It's a temporary fix, but seemed to work for us.

**Comment by bradyvercher** [comment]
This fix was implemented well before the issue, so I'm not sure why it would have been a problem, but I'm going to go ahead and close this out.
