### ISSUE TITLE
gform_theme_config is not defined

### ISSUE THREAD

**Issue by augusto97** [cedaro/gravity-forms-iframe#74]
When inserting the form in another site I get this error in the console:

Uncaught ReferenceError: gform_theme_config is not defined
    at 3856 (scripts-theme.min.js?ver=f4d12a887a23a8c5755fd2b956bc8fcf:1:2232)
    at o (scripts-theme.min.js?ver=f4d12a887a23a8c5755fd2b956bc8fcf:1:2382)
    at scripts-theme.min.js?ver=f4d12a887a23a8c5755fd2b956bc8fcf:1:4102
    at o.O (scripts-theme.min.js?ver=f4d12a887a23a8c5755fd2b956bc8fcf:1:2679)
    at scripts-theme.min.js?ver=f4d12a887a23a8c5755fd2b956bc8fcf:1:4117
    at scripts-theme.min.js?ver=f4d12a887a23a8c5755fd2b956bc8fcf:1:4122

 It does not affect the operation, but I would like that error not to appear. Is there a way to fix it?

**Comment by bradyvercher** [comment]
I believe this should be fixed in e0721625e30e79458375df3b30e4ae868c07c60a
